services:
  grafana:
    container_name: 'jpl-honeycomb-panel-grafana'

    build:
      context: ./.config
      dockerfile: grafana.dockerfile
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.2.0}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3001:3000/tcp
    depends_on:
      - influxdb
    links:
      - "influxdb:db"
    volumes:
      - ./dist:/var/lib/grafana/plugins/jpl-honeycomb-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/jpl-honeycomb-panel
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.jpl-honeycomb-panel:debug
      GF_LOG_LEVEL: error
      # GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: jpl-honeycomb-panel
      GF_INFLUX_ADMIN_TOKEN: v6P34mao7UYHblkpDJYt8fmWLw1L79Z77sg3RDgScxHtiYwDO0cowbzOHnHK2ZamDljF6ehNEq8ucRQF-Hr0RA==

  influxdb:
    image: influxdb:2
    container_name: jpl-honeycomb-panel-influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: v6P34mao7UYHblkpDJYt8fmWLw1L79Z77sg3RDgScxHtiYwDO0cowbzOHnHK2ZamDljF6ehNEq8ucRQF-Hr0RA==
      DOCKER_INFLUXDB_INIT_ORG: honeycomb
      DOCKER_INFLUXDB_INIT_BUCKET: honeycomb
    ports:
      - 8087:8086/tcp

  influxdb-setup:
    depends_on:
      - influxdb
    restart: "no"
    build:
      context: ./.config
      dockerfile: influxdb.dockerfile
      args:
         INFLUXDB_TOKEN: v6P34mao7UYHblkpDJYt8fmWLw1L79Z77sg3RDgScxHtiYwDO0cowbzOHnHK2ZamDljF6ehNEq8ucRQF-Hr0RA==
